-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 19:22:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`binomage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`binomage` (
  `idbinomage` INT NOT NULL,
  `nom_binomage` VARCHAR(50) NULL,
  PRIMARY KEY (`idbinomage`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`filleul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`filleul` (
  `idfilleul` INT NOT NULL,
  `photo_filleul` TINYTEXT NULL,
  `binomage_idbinomage` INT NOT NULL,
  PRIMARY KEY (`idfilleul`, `binomage_idbinomage`),
  CONSTRAINT `fk_filleul_binomage`
    FOREIGN KEY (`binomage_idbinomage`)
    REFERENCES `mydb`.`binomage` (`idbinomage`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `mydb`.`parrain`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parrain` (
  `idparrain` INT NOT NULL,
  `photo_parrain` TINYTEXT NULL,
  `binomage_idbinomage` INT NOT NULL,
  PRIMARY KEY (`idparrain`, `binomage_idbinomage`),
  CONSTRAINT `fk_parrain_binomage1`
    FOREIGN KEY (`binomage_idbinomage`)
    REFERENCES `mydb`.`binomage` (`idbinomage`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


